all: question_two question_three question_four question_five
clean:
	@rm question_two question_three question_four question_five JUNK.txt

question_two:
	@g++ question_two.c -o question_two

question_three:
	@g++ question_three.c -o question_three

question_four:
	@g++ question_four.c -o question_four

question_five:
	@g++ question_five.c -o question_five
