bstat:
	@gcc -g \
		-Wall \
		-Wshadow \
		-Wunreachable-code \
		-Wredundant-decls \
		-Wmissing-declarations \
		-Wold-style-definition \
		-Wmissing-prototypes \
		-Wdeclaration-after-statement \
		bstat.c \
		-o bstat

clean:
	rm bstat

loop: clean bstat
