stages:
  - test

test:
  stage: test
  image: rust:latest
  # cache:
  #   key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  #   paths:
  #     - cargo/
  #     - target/
  before_script:
    - export CARGO_HOME="$CI_PROJECT_DIR/cargo"
    - rustup --version
    - rustc --version
    - cargo --version
  script:
    - cargo test --all --verbose
